language: c

install:
- sudo apt-get install mono-devel mono-gmcs nunit-console

script:
- xbuild CI.proj
- nunit-console ./src/ArcGIS.Test/bin/Release/ArcGIS.Test.dll -exclude Integration,NotWorkingOnMono
