language: node_js
node_js:
  - "0.11"
  - "0.10"

branches:
  only:
    - dev

before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 0.11
