// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyCopyrightAttribute("Copyright Dave Timmins (c) 2013")]
[assembly: AssemblyProductAttribute("ArcGIS REST API ServiceModel PCL")]
[assembly: AssemblyVersionAttribute("5.9.0")]
[assembly: AssemblyFileVersionAttribute("5.9.0")]
[assembly: AssemblyInformationalVersionAttribute("5.9.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyCompany = "";
        internal const System.String AssemblyCopyright = "Copyright Dave Timmins (c) 2013";
        internal const System.String AssemblyProduct = "ArcGIS REST API ServiceModel PCL";
        internal const System.String AssemblyVersion = "5.9.0";
        internal const System.String AssemblyFileVersion = "5.9.0";
        internal const System.String AssemblyInformationalVersion = "5.9.0";
    }
}
